# Generated by Django 6.0.5 on 2026-05-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dept_type', models.CharField(choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('logistics', 'Logistics'), ('creative', 'Creative'), ('operations', 'Operations')], default='operations', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='clients.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
